version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/localdb
      SPRING_DATASOURCE_USERNAME: localdb
      SPRING_DATASOURCE_PASSWORD: localdb
      SPRING_APPLICATION_NAME: tangerine-api
      SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY: ${AWS_ACCESS_KEY}
      SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY: ${AWS_SECRET_KEY}
      SPRING_CLOUD_AWS_REGION_STATIC: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: localdb
      POSTGRES_PASSWORD: localdb
    ports:
      - '5432:5432'